global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # System metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  # Your Cloud Run service (we'll add metrics endpoint)
  - job_name: 'nyc-taxi-api'
    scrape_interval: 30s
    static_configs:
      - targets: ['your-cloud-run-service-url']  # We'll update this
    metrics_path: '/metrics'
