global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'nyc-taxi-api'
    scrape_interval: 30s
    static_configs:
      - targets: ['nyc-taxi-predictor-980676408017.a.run.app']  # Your Cloud Run URL (without https://)
    metrics_path: '/metrics'
    scheme: 'https'
