data:
  raw_path: "data/raw"
  processed_path: "data/processed"

model:
  name: "random_forest_regressor"
  params:
    n_estimators: 50
    max_depth: 10
    random_state: 42

mlflow:
  # --- IMPORTANT ---
  # Replace this placeholder with your actual GCP MLFlow server IP address
  tracking_uri: "http://34.170.162.73:5000"
  experiment_name: "nyc-taxi-trip-duration"
